version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports: 
      - "64000:80"

  clientservice:
    image: clientservice
    build:
      context: .
      dockerfile: ClientService/Dockerfile
    ports: 
      - "64001:80"

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports: 
      - "64002:80"

  zookeeper: 
    image: wurstmeister/zookeeper:3.4.6 
    ports: 
      - "2181:2181"

  kafka: 
    image: wurstmeister/kafka
    ports: 
      - "9092:9092" 
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0 
      KAFKA_CREATE_TOPICS: "Clients-Topic,Products-Topic" 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
    volumes:                                                                                                                                                                                                 
      - /var/run/docker.sock:/var/run/docker.sock 

  kafkarestproxy:
    image: confluentinc/cp-kafka-rest:4.1.0
    environment: 
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_HOST_NAME: kafkarestproxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      ACCESS_CONTROL_ALLOW_ORIGIN_DEFAULT: "*"
      ACCESS_CONTROL_ALLOW_ORIGIN_METHODS: "*"
